name: 缺陷报告
description: 报告可以稳定复现的问题
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: 问题描述
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
    validations:
      required: true
  - type: input
    attributes:
      label: Campus Admin 版本
    validations:
      required: true
  - type: input
    attributes:
      label: Vue、浏览器和操作系统版本
    validations:
      required: true
