export { CampusApplication, createCampus, definePlugin, defineProvider } from './application'
export type { CampusApplicationOptions, CampusLifecycle } from './application'
export { CampusContainer, isCampusProvider } from './container'
export { CampusContext } from './context'
export type { CampusConfig } from './contracts/config'
export type { CampusPlugin, CampusProvider } from './contracts/provider'
export { campus, getCurrentCampus, setCurrentCampus } from './facade'
